// src/components/state-counters/Counter.vue
<script setup lang="ts">
import { countState } from '@store/CounterStore';
import { useStore } from '@nanostores/vue';

const $count = useStore(countState);
</script>

<template>
  <div class="flex items-center gap-8 justify-center">
    <button @click="countState.set($count + 1)">+</button>
    <p>Vue count is: {{ $count }}</p>
    <button @click="countState.set($count - 1)">-</button>
  </div>
</template>

// src/components/counters/Counter.tsx
import { createSignal } from 'solid-js';

const Counter = () => {
  const [count, setCount] = createSignal(0);
  return (
    <div class='flex items-center gap-8 justify-center'>
      <button onClick={() => setCount(count() + 1)}>+</button>
      <p>Solid Count is: {count()}</p>
      <button onClick={() => setCount(count() - 1)}>-</button>
    </div>
  );
};

export default Counter;
